#!/usr/bin/env bash
#
# install.sh — install the shared bootcamp_utils library so that every notebook
# can simply do `from bootcamp_utils import ...` from ANY session folder, with
# no sys.path hacks.
#
# This is safe to run many times. It performs an EDITABLE install, so if you
# later edit the library the notebooks pick up the changes with no reinstall.
#
# Run it once when building/preparing a KV260 image:
#     bash install.sh
#
# (The bootcamp-utils.service unit in this folder runs this automatically on
#  first boot of a freshly flashed image — see README for details.)

set -e

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Installing shared bootcamp_utils library from: $HERE"

# ---------------------------------------------------------------------------
# 1) Preferred: install as a real, importable package (editable, so edits are
#    picked up live). This makes `import bootcamp_utils` work everywhere.
# ---------------------------------------------------------------------------
python3 -m pip install -e "$HERE" --no-build-isolation \
  || python3 -m pip install -e "$HERE" \
  || echo "pip install failed (offline?); relying on IPython startup fallback below."

# ---------------------------------------------------------------------------
# 2) Belt-and-suspenders fallback: drop an IPython startup script that adds this
#    folder to sys.path at kernel start. This guarantees `import bootcamp_utils`
#    works in every Jupyter notebook even if pip install could not run (e.g. no
#    network on first boot). Zero per-notebook code required.
# ---------------------------------------------------------------------------
STARTUP_DIR="${HOME}/.ipython/profile_default/startup"
mkdir -p "$STARTUP_DIR"
cat > "$STARTUP_DIR/00-bootcamp-utils-path.py" <<PYEOF
# Auto-generated by bootcamp_sessions/install.sh
# Makes the shared bootcamp_utils library importable in every notebook.
import sys
_SHARED = r"$HERE"
if _SHARED not in sys.path:
    sys.path.insert(0, _SHARED)
PYEOF
echo "Installed IPython startup fallback at: $STARTUP_DIR/00-bootcamp-utils-path.py"

echo "Done. Verifying import ..."
python3 - <<'PY'
import importlib, sys
try:
    import bootcamp_utils
    print("OK: import bootcamp_utils works (version %s)" % bootcamp_utils.__version__)
except Exception as e:
    print("WARNING: could not import bootcamp_utils yet:", e)
    sys.exit(0)
PY
